### ISSUE TITLE
Caused by: org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements Connector and which name matches com.amazon.kinesis.kafka.AmazonKinesisSinkConnector

### ISSUE THREAD

**Issue by snehamj** [awslabs/kinesis-kafka-connector#17]
1) Cloned the git repo
2) mvn clean package
3) Copied the `amazon-kinesis-kafka-connecter-0.0.8-SNAPSHOT.jar` to JAVA_HOME/lib/ext
4) Made changes to worker.properties and kinesis-kafka-streams-connecter.properties
5) Started the standalone connector using:
`connect-standalone kinesis-kafka-connector/config/worker.properties kinesis-kafka-connector/config/kinesis-streams-kafka-connector.properties`
6) But I get the following error:

`[2017-12-07 11:56:06,858] ERROR Failed to create job for /Users/Desktop/kinesis-kafka-connector/config/kinesis-streams-kafka-connector.properties (org.apache.kafka.connect.cli.ConnectStandalone:89)
[2017-12-07 11:56:06,859] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:100)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements Connector and which name matches com.amazon.kinesis.kafka.AmazonKinesisSinkConnector, available connectors are: PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSinkConnector, name='org.apache.kafka.connect.file.FileStreamSinkConnector', version='0.11.0.1', encodedVersion=0.11.0.1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSourceConnector, name='org.apache.kafka.connect.file.FileStreamSourceConnector', version='0.11.0.1', encodedVersion=0.11.0.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name='org.apache.kafka.connect.tools.MockConnector', version='0.11.0.1', encodedVersion=0.11.0.1, type=connector, typeName='connector', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='0.11.0.1', encodedVersion=0.11.0.1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='0.11.0.1', encodedVersion=0.11.0.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='0.11.0.1', encodedVersion=0.11.0.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='0.11.0.1', encodedVersion=0.11.0.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='0.11.0.1', encodedVersion=0.11.0.1, type=source, typeName='source', location='classpath'}
	at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:79)
	at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:66)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:97)
Caused by: org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements Connector and which name matches com.amazon.kinesis.kafka.AmazonKinesisSinkConnector, available connectors are: PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSinkConnector, name='org.apache.kafka.connect.file.FileStreamSinkConnector', version='0.11.0.1', encodedVersion=0.11.0.1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSourceConnector, name='org.apache.kafka.connect.file.FileStreamSourceConnector', version='0.11.0.1', encodedVersion=0.11.0.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name='org.apache.kafka.connect.tools.MockConnector', version='0.11.0.1', encodedVersion=0.11.0.1, type=connector, typeName='connector', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='0.11.0.1', encodedVersion=0.11.0.1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='0.11.0.1', encodedVersion=0.11.0.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='0.11.0.1', encodedVersion=0.11.0.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='0.11.0.1', encodedVersion=0.11.0.1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='0.11.0.1', encodedVersion=0.11.0.1, type=source, typeName='source', location='classpath'}
	at org.apache.kafka.connect.runtime.isolation.Plugins.newConnector(Plugins.java:165)
	at org.apache.kafka.connect.runtime.AbstractHerder.getConnector(AbstractHerder.java:341)
	at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:240)
	at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:157)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:94)
[2017-12-07 11:56:06,864] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:65)
[2017-12-07 11:56:06,865] INFO Stopping REST server (org.apache.kafka.connect.runtime.rest.RestServer:154)
[2017-12-07 11:56:06,884] INFO Stopped ServerConnector@5769679b{HTTP/1.1}{0.0.0.0:8083} (org.eclipse.jetty.server.ServerConnector:306)
[2017-12-07 11:56:06,893] INFO Stopped o.e.j.s.ServletContextHandler@4b7ab262{/,null,UNAVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:865)
[2017-12-07 11:56:06,896] INFO REST server stopped (org.apache.kafka.connect.runtime.rest.RestServer:165)
[2017-12-07 11:56:06,897] INFO Herder stopping (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:76)
[2017-12-07 11:56:06,897] INFO Worker stopping (org.apache.kafka.connect.runtime.Worker:156)
[2017-12-07 11:56:06,898] INFO Stopped FileOffsetBackingStore (org.apache.kafka.connect.storage.FileOffsetBackingStore:67)
[2017-12-07 11:56:06,898] INFO Worker stopped (org.apache.kafka.connect.runtime.Worker:176)
[2017-12-07 11:56:06,898] INFO Herder stopped (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:86)
[2017-12-07 11:56:06,898] INFO Kafka Connect stopped (org.apache.kafka.connect.runtime.Connect:70)`

I installed Kafka using homebrew and the version is `0.11.0.1`. Please let me know how I can get this working. Thank you!

**Comment by kprakashmca** [comment]
Did you fixed the issue. I'm in the same boat, please shed ome light if you have fixed the issue.

Thanks.

**Comment by JoeShi** [comment]
I also run into this issue.

**Comment by liruikaiyao** [comment]
just add plugin.path="your confluentinc-kafka-connect-kinesis path" in your worker.properties
