### ISSUE TITLE
com.google.common.collect.Sets$SetView.iterator() Exception in thread "main" java.lang.NoSuchMethodError:

### ISSUE THREAD

**Issue by ajaysamant** [awslabs/kinesis-kafka-connector#21]
It has been very difficult experience using this connector for my use case.

First i had to comment few lines in stop method line 293...it was giving Nullpointerexception..
then when i dropped the new jar file now its giving NoSuchMethodError.

Not sure if i should try to use this connector for my use case or think of some other options..

**Comment by nehalmehta** [comment]
Hi @ajaysamant 

Have you added connector artifact to classpath? You can also add path of artifact in worker properties file plugin.path=/sompath/ 

I think there is some conflict when you are adding to classpath. Try to add properties plugin.path in worker properties

Thanks,
Nehal

**Comment by ajaysamant** [comment]
I did that...
after doing the maven build - which was successful - i added this line in worker.properties
last 3 lines ...

schemas.enable=false
rest.port=8888
plugin.path=**/home/ec2-user/kinesis-kafka-connector/lib**


the jar files are under target folder..

its picking up from aws jdk jar file

[2018-03-05 17:45:18,150] INFO Scanning for plugin classes. This might take a moment ... (org.apache.kafka.connect.cli.ConnectStandalone:74)
[2018-03-05 17:45:18,165] INFO Loading plugin from: /home/ec2-user/kinesis-kafka-connector/lib/aws-java-sdk-1.11.289.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:179)
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:380)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanPluginPath(DelegatingClassLoader.java:258)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanUrlsAndAddPlugins(DelegatingClassLoader.java:201)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.registerPlugin(DelegatingClassLoader.java:193)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initLoaders(DelegatingClassLoader.java:153)
	at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:47)

**Comment by nehalmehta** [comment]
@ajaysamant Have you moved JAR files to /home/ec2-user/kinesis-kafka-connector/lib? Do they have appropriate permission?

**Comment by ushulau** [comment]
same issue here `no such method` looks like version issue I'm using kafka 2.12 and same aws library

**Comment by uncodead** [comment]
try to insert this at pom.xml:

                <dependency>
                         <groupId>com.google.guava</groupId>
                         <artifactId>guava</artifactId>
                         <version>27.0-jre</version>
                </dependency>

run _mvn package_, and copy to classpath

**Comment by chickensoup** [comment]
Don't use the big connector since it may contains libs that duplicates with other libs. Try use the original-amazon-kinesis-kafka-connecter-0.0.9-SNAPSHOT.jar and copy the necessary jars into libs.

**Comment by AlejandroKolio** [comment]
Try to disable proxy
![image](https://user-images.githubusercontent.com/10224161/59436958-4a093000-8df9-11e9-9d8d-78a47d545007.png)
