### ISSUE TITLE
 java.io.IOException: Could not create tmp dir /tmp/amazon-kinesis-producer-native-binaries         at com.amazonaws.services.kinesis.producer.KinesisProducer.extractBinaries(KinesisProducer.java:885) 

### ISSUE THREAD

**Issue by Vidyats1** [awslabs/kinesis-kafka-connector#55]
```
 INFO Extracting binaries to /tmp/amazon-kinesis-producer-native-binaries (com.amazonaws.services.kinesis.producer.KinesisProducer:881)
[2021-03-10 05:11:20,904] ERROR WorkerSinkTask{id=kafka-kinesis-streams-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:187)
java.lang.RuntimeException: Could not copy native binaries to temp directory /tmp/amazon-kinesis-producer-native-binaries
        at com.amazonaws.services.kinesis.producer.KinesisProducer.extractBinaries(KinesisProducer.java:908)
        at com.amazonaws.services.kinesis.producer.KinesisProducer.<init>(KinesisProducer.java:245)
        at com.amazon.kinesis.kafka.AmazonKinesisSinkTask.getKinesisProducer(AmazonKinesisSinkTask.java:362)
        at com.amazon.kinesis.kafka.AmazonKinesisSinkTask.open(AmazonKinesisSinkTask.java:296)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.openPartitions(WorkerSinkTask.java:640)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.access$1100(WorkerSinkTask.java:71)
        at org.apache.kafka.connect.runtime.WorkerSinkTask$HandleRebalance.onPartitionsAssigned(WorkerSinkTask.java:705)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.invokePartitionsAssigned(ConsumerCoordinator.java:293)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:430)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:451)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:367)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:508)
        at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1257)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1226)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1206)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:457)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:324)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
        Suppressed: java.lang.NullPointerException
                at com.amazon.kinesis.kafka.AmazonKinesisSinkTask.close(AmazonKinesisSinkTask.java:304)
                at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:410)
                at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:644)
                at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:202)
                ... 7 more
Caused by: java.io.IOException: Could not create tmp dir /tmp/amazon-kinesis-producer-native-binaries
        at com.amazonaws.services.kinesis.producer.KinesisProducer.extractBinaries(KinesisProducer.java:885)
        ... 25 more
```

I am getting the above error while trying to publish data from Kafka to Kinesis. I tried this with both docker and native Kafka on Linux and it throws me the same error. Please let me know how to overcome this.

**Comment by rptr94** [comment]
you can change the configuation. like
        config.setTempDirectory("/usr/tmp/");
