### ISSUE TITLE
Caused by: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector config {internal.key.converter=org.apache.kafka.connect.json.JsonConverter, key.converter.schemas.enable=true, offset.storage.file.filename=offset.log, internal.value.converter.schemas.enable=true, internal.value.converter=org.apache.kafka.connect.json.JsonConverter, value.converter.schemas.enable=true, bootstrap.servers=127.0.0.1:9092, value.converter=org.apache.kafka.connect.storage.StringConverter, internal.key.converter.schemas.enable=true, key.converter=org.apache.kafka.connect.storage.StringConverter, schemas.enable=false} contains no connector type

### ISSUE THREAD

**Issue by kapjoshi-cisco** [awslabs/kinesis-kafka-connector#69]
Hi,
I get the below error while using this connector for kafka source to kinesis firehose as sink. 

Started kafka cluster using [quick start](https://kafka.apache.org/documentation/#quickstart) link

kafka version 
```bash
kafka/bin/kafka-topics.sh --version                                                                                                       
3.1.0
```

Running configs:
1) worker.properties
```bash
bootstrap.servers=127.0.0.1:9092
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
#internal.value.converter=org.apache.kafka.connect.storage.StringConverter
#internal.key.converter=org.apache.kafka.connect.storage.StringConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=true
value.converter.schemas.enable=true
internal.key.converter.schemas.enable=true
internal.value.converter.schemas.enable=true
offset.storage.file.filename=offset.log
schemas.enable=false
```
2) kinesis-firehose-kafka-connector.properties
```bash
name=KAFKA_CONNECTOR
connector.class=com.amazon.kinesis.kafka.FirehoseSinkConnector
tasks.max=1
topics=quickstart-events
region=us-west-2
batch=true
batchSize=500
batchSizeInBytes=3670016
deliveryStream=kafka-test
```
3) plugin_path in `/kafka/config/connect-standalone.properties`
```bash
plugin.path=/usr/local/share/java,/usr/local/share/kafka/plugins,/opt/connectors,/usr/lib/jvm/java-11/lib/
```
Error trace:
```bash
2022-03-13 11:39:39,479] ERROR Failed to create job for /home/ec2-user/environment/kinesis-kafka-connector/config/worker.properties (org.apache.kafka.connect.cli.ConnectStandalone:107)
[2022-03-13 11:39:39,490] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:117)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector config {internal.key.converter=org.apache.kafka.connect.json.JsonConverter, key.converter.schemas.enable=true, offset.storage.file.filename=offset.log, internal.value.converter.schemas.enable=true, internal.value.converter=org.apache.kafka.connect.json.JsonConverter, value.converter.schemas.enable=true, bootstrap.servers=127.0.0.1:9092, value.converter=org.apache.kafka.connect.storage.StringConverter, internal.key.converter.schemas.enable=true, key.converter=org.apache.kafka.connect.storage.StringConverter, schemas.enable=false} contains no connector type
        at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:115)
        at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:99)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:114)
Caused by: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector config {internal.key.converter=org.apache.kafka.connect.json.JsonConverter, key.converter.schemas.enable=true, offset.storage.file.filename=offset.log, internal.value.converter.schemas.enable=true, internal.value.converter=org.apache.kafka.connect.json.JsonConverter, value.converter.schemas.enable=true, bootstrap.servers=127.0.0.1:9092, value.converter=org.apache.kafka.connect.storage.StringConverter, internal.key.converter.schemas.enable=true, key.converter=org.apache.kafka.connect.storage.StringConverter, schemas.enable=false} contains no connector type
        at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:424)
        at org.apache.kafka.connect.runtime.AbstractHerder.lambda$validateConnectorConfig$2(AbstractHerder.java:362)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
[2022-03-13 11:39:39,493] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:67)
[2022-
```
Any pointers will be useful.

Thanks

**Comment by kapjoshi-cisco** [comment]
This fixed the issue [stackoverflow-link](https://stackoverflow.com/questions/53947583/mongodb-debezium-connector-config-contains-no-connector-type)
>connect-standalone.properties and connect-standalone-worker.properties need to be one file
