### ISSUE TITLE
Please help: Connecter Error "Pipes did not show up after calling mkfifo"

### ISSUE THREAD

**Issue by guoxun19** [awslabs/kinesis-kafka-connector#7]
Hi,
I met with the error log when running connect-standalone.sh, could you please help me? Thank you~

Sep 18, 2017 3:50:11 PM com.google.common.util.concurrent.ExecutionList executeListener
SEVERE: RuntimeException while executing runnable com.google.common.util.concurrent.Futures$6@66177362 with executor INSTANCE
org.apache.kafka.connect.errors.DataException: Exception during Kinesis put
	at com.amazon.kinesis.kafka.AmazonKinesisSinkTask$1.onFailure(AmazonKinesisSinkTask.java:60)
	at com.google.common.util.concurrent.Futures$6.run(Futures.java:1310)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:202)
	at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:68)
	at com.amazonaws.services.kinesis.producer.KinesisProducer$MessageHandler$2.run(KinesisProducer.java:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.amazonaws.services.kinesis.producer.IrrecoverableError: Pipes did not show up after calling mkfifo
	at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:520)
	at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:492)
	at com.amazonaws.services.kinesis.producer.Daemon.createPipesUnix(Daemon.java:405)
	at com.amazonaws.services.kinesis.producer.Daemon.createPipes(Daemon.java:358)
	at com.amazonaws.services.kinesis.producer.Daemon.access$000(Daemon.java:62)
	at com.amazonaws.services.kinesis.producer.Daemon$1.run(Daemon.java:131)

**Comment by guoxun19** [comment]
Pipe will be create in directory /tmp/amazon-kinesis-producer-native-binaries/ by default, the user running connect-standalone.sh should have permission to write to the directory. Issue resolved, thank you.
